import React, { Fragment } from 'react'
import { FiBell } from 'react-icons/fi'
import Button from '../components/Button'
import Icon from '../components/Icon'

export const Home: React.FC = () => {
  return (
    <Fragment>
      <h1>Redux + TypeScript</h1>
      <p>
        Hello and welcome! :) This app was generated by the Create React App
        template and bootstrapped with Redux, React Router, TypeScript, ESlint,
        Prettier for you. Take a look around ;)
      </p>
      <Button
        childrenIcon={
          <Icon>
            <FiBell />
          </Icon>
        }
        icon={false}
        secundary
        disabled={false}
        ghost
        large={false}
        small={false}
      >
        Button
      </Button>
    </Fragment>
  )
}
